package ludo;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cartoonmed
 */
public class BoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        LayerBG = new javax.swing.JLayeredPane();
        LayerP1_1 = new javax.swing.JLayeredPane();
        LabelP1_1 = new javax.swing.JLabel();
        LabelBG = new javax.swing.JLabel();
        
        //==Add BG 
        Icon BG = new ImageIcon("../Ludo/img/Ludo.jpg");
        LabelBG = new JLabel(BG);
        //==
        
        //==Add BG 
        Icon P1_1 = new ImageIcon("../Ludo/img/Red.png");
        LabelP1_1 = new JLabel(P1_1);

        //==

        setBackground(new java.awt.Color(255, 51, 51));
        setPreferredSize(new java.awt.Dimension(650, 650));

        LabelP1_1.setBounds(100, 100, 50, 50);
        LayerP1_1.add(LabelP1_1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LayerP1_1.setBounds(0, 0, 650, 650);
        LayerBG.add(LayerP1_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LabelBG.setBounds(0, 0, 650, 650);
        LayerBG.add(LabelBG, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayerBG, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayerBG, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    private javax.swing.JLabel LabelBG;
    private javax.swing.JLabel LabelP1_1;
    private javax.swing.JLayeredPane LayerBG;
    private javax.swing.JLayeredPane LayerP1_1;
    // End of variables declaration
}
