/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cartoonmed
 */
public class BoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayerBG = new javax.swing.JLayeredPane();
        LayerP1_1 = new javax.swing.JLayeredPane();
        LayerP2_1 = new javax.swing.JLayeredPane();
        bt_roll_die = new javax.swing.JButton();
        LabelP2_1 = new javax.swing.JLabel();
        LabelP1_1 = new javax.swing.JLabel();
        LabelBG = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 51, 51));
        setPreferredSize(new java.awt.Dimension(650, 650));

        bt_roll_die.setText("Die");
        bt_roll_die.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_roll_dieActionPerformed(evt);
            }
        });
        bt_roll_die.setBounds(570, 580, 80, 70);
        LayerP2_1.add(bt_roll_die, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LabelP2_1.setBounds(0, 0, 650, 650);
        LayerP2_1.add(LabelP2_1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LayerP2_1.setBounds(0, 0, 650, 650);
        LayerP1_1.add(LayerP2_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LabelP1_1.setBounds(0, 0, 650, 650);
        LayerP1_1.add(LabelP1_1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LayerP1_1.setBounds(0, 0, 650, 650);
        LayerBG.add(LayerP1_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LabelBG.setBounds(0, 0, 650, 650);
        LayerBG.add(LabelBG, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayerBG, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayerBG, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_roll_dieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_roll_dieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_roll_dieActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBG;
    private javax.swing.JLabel LabelP1_1;
    private javax.swing.JLabel LabelP2_1;
    private javax.swing.JLayeredPane LayerBG;
    private javax.swing.JLayeredPane LayerP1_1;
    private javax.swing.JLayeredPane LayerP2_1;
    private javax.swing.JButton bt_roll_die;
    // End of variables declaration//GEN-END:variables
}
